apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # imagePullSecrets: {{ .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.frontend.imagePullSecrets | nindent 8 }}  # 引用 imagePullSecrets
      containers:
      - name: frontend
        # image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        image: {{ .Values.frontend.image.repository }}:380
        imagePullPolicy: Always  # 确保每次都尝试拉取最新镜像
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80